### ISSUE TITLE
Error on migrate:fresh

### ISSUE THREAD

**Issue by pabloblazquez** [tomatophp/filament-ecommerce#2]
SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint (Connection: mysql, SQL: alter table `orders` add constraint `orders_address_id_foreign` foreign key (`address_id`) references `locations` (`id`) on delete cascade)

![image](https://github.com/user-attachments/assets/952441c1-6219-4bd6-9d0c-6f1ccc439321)

**Comment by 3x1io** [comment]
hi @pabloblazquez thanks for your report, yes it was a problem on filament-locations and it's fixed now you can try it

**Comment by YonkoSam** [comment]
![image](https://github.com/user-attachments/assets/1d52b58a-94f6-4c8e-929c-59b14becd04a)

**Comment by YonkoSam** [comment]
im having a similer problem its fresh install laravel with filment

**Comment by 3x1io** [comment]
what is your database driver?

**Comment by YonkoSam** [comment]
sqllite

**Comment by 3x1io** [comment]
it's fine now i fix the seeder for SQLite

**Comment by YonkoSam** [comment]
yes the first problem is fixed but now  there is a another one 
![image](https://github.com/user-attachments/assets/99fb78ee-3be2-47f9-b8c5-e54c290c71ab)

**Comment by 3x1io** [comment]
use this and than migrate

```bash
php artisan vendor:publish --provider="Spatie\LaravelSettings\LaravelSettingsServiceProvider" --tag="migrations"
```

I add it to docs

**Comment by YonkoSam** [comment]
thank you it worked

**Comment by pabloblazquez** [comment]
I still have problems launching a "migrate fresh". Now the problema is with "base_tomato_ecommerce.settings'"

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'base_tomato_ecommerce.settings' doesn't exist (Connection: mysql, SQL: select exists(select * from `settings` where `group` = ordering and `name` = ordering_web_branch) as `exists`)

![image](https://github.com/user-attachments/assets/96ae8ea2-7684-4822-ae5c-82b686f551fa)

**Comment by 3x1io** [comment]
if you check the docs

```php
php artisan vendor:publish --provider="Spatie\LaravelSettings\LaravelSettingsServiceProvider" --tag="migrations"
php artisan filament-settings-hub:install
```

**Comment by pabloblazquez** [comment]
You're right, sorry, my bad. It went well this time.

I will try your development, good job!
